### ISSUE TITLE
Strange issue when manually testing with ./contrib/tesh.sh

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-secp256k1#310] opened 2021-06-19 11:05 UTC
When I do a manual testing on rust nightly with `DO_FEATURE_MATRIX=true ./contrib/test.sh` command I am getting doctest case failure on signature verification (only under one specific tested feature combination):

<details>
   <summary>Test log</summary>

```
   Doc-tests secp256k1
     Running `rustdoc --crate-type lib --crate-name secp256k1 --test /Users/orlovsky/Repositories/bitcoin/rust-secp256k1/src/lib.rs -L dependency=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps -L dependency=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps -L native=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/build/secp256k1-sys-1ee109edaf08fd4f/out --extern bitcoin_hashes=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps/libbitcoin_hashes-b2e798701dab4969.rlib --extern rand=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps/librand-5ab06a9cb5ba4550.rlib --extern rand_core=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps/librand_core-92e42927a2b53f93.rlib --extern secp256k1=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps/libsecp256k1-fdf981b15c627475.rlib --extern secp256k1_sys=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps/libsecp256k1_sys-2ce3be3ac1e8d0d6.rlib --extern serde_test=/Users/orlovsky/Repositories/bitcoin/rust-secp256k1/target/debug/deps/libserde_test-7ee01c75ec5537d3.rlib -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="std"' --error-format human`

running 5 tests
test src/lib.rs - Secp256k1<C>::verify (line 798) ... ok
test src/lib.rs - (line 39) ... ok
test src/lib.rs - (line 59) ... ok
test src/ecdh.rs - ecdh::SharedSecret::new_with_hash (line 129) ... ok
test src/lib.rs - (line 75) ... FAILED

failures:

---- src/lib.rs - (line 75) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: secp.verify(&message, &sig, &public_key).is_ok()', src/lib.rs:35:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



failures:
    src/lib.rs - (line 75)

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.72s
```
</details>

**Comment by apoelstra** [comment] 2021-07-07 17:12
Does this still happen with a more recent nightly?

**Comment by dr-orlovsky** [comment] 2021-08-01 14:20
It does (nightly-x86_64-apple-darwin), with the current master tip

**Comment by apoelstra** [comment] 2021-09-08 20:56
Can you try running in a debugger?

**Comment by sanket1729** [comment] 2021-09-14 03:58
Not able to reproduce it on the current master tip with latest nightly as of Sept 13th

**Comment by tcharding** [comment] 2022-11-24 00:58
Cannot reproduce, perhaps we can close this?

**Closed** 2022-11-24 05:14 UTC
